import assert from 'node:assert/strict';
import { fingerprint, seoInputs } from './semantic-html.mjs';
import { buildManifest, diff, batches, sitemapChunks, validate } from './manifest.mjs';
import { sitemapRewrites, sitemapIndexXml } from '../../seo/sitemap-policy.js';

const origin = 'https://helpingyourboyfriend.org';
const t1 = '2026-10-08T00:00:00.000Z', t2 = '2026-10-09T01:00:00.000Z';
const html = (path, body = 'A useful player guide') => `<html lang="en"><head><title>Title ${path}</title><meta name="description" content="Game guide"><meta name="robots" content="index, follow"><link rel="canonical" href="${origin}${path}"></head><body><nav><a href="/endings">Endings</a></nav><main><h1>Helping Your Boyfriend</h1><p class="pink">${body}</p><img src="/images/a.png" alt="Adrian"></main><time datetime="2026-10-08">Updated 2026-10</time><footer>Copyright © 2026 Helping Your Boyfriend</footer><script>buildId="one"</script><script type="application/ld+json">{"@type":"WebPage","name":"Player guide","dateModified":"2026-10-08"}</script></body></html>`;
const entry = (path, content = html(path)) => ({ path, canonicalUrl: `${origin}${path}`, indexable: seoInputs(content).indexable, contentFingerprint: fingerprint(content), siteUrl: origin, contentTime: t1, priority: path === '/' ? 1 : .8, changeFrequency: 'monthly' });
const candidates = [entry('/'), entry('/characters'), entry('/controls'), entry('/endings')];
const first = buildManifest(candidates, null, t1);
const same = buildManifest(candidates, first, t2);
assert.deepEqual(same.entries, first.entries, 'Unchanged dates survive later build');
assert.equal(diff(first, same).unchanged.length, 4);
assert.equal(diff(first, same).updated.length, 0);
const independent = buildManifest(candidates.map(e => e.path === '/controls' ? entry('/controls', html('/controls', 'New controls help')) : e), first, t2);
assert.deepEqual(diff(first, independent).updated, [`${origin}/controls`]);
const shared = buildManifest(candidates.map(e => entry(e.path, html(e.path).replace('>Endings<','>All endings<'))), first, t2);
assert.equal(diff(first, shared).updated.length, 4);
const cosmetic = html('/').replace('class="pink"', 'class="new-layout" style="padding: 20px"').replace('buildId="one"', 'buildId="two"').replace('© 2026', '© 2027').replace('datetime="2026-10-08"','datetime="2026-10-09"').replace('dateModified":"2026-10-08"','dateModified":"2026-10-09"');
assert.equal(fingerprint(cosmetic), fingerprint(html('/')), 'Classes/styles/build IDs/decoration/dates ignored');
assert.equal(fingerprint(html('/').replace('<body>','<body>\n  ').replace('</main>', '\n</main>')), fingerprint(html('/')), 'HTML formatting ignored');
assert.equal(fingerprint(html('/').replace('/images/a.png','/images/a.png?dpl=dpl_abc')),fingerprint(html('/')),'Vercel deployment-affinity asset query ignored');
const contact = html('/contact','support@helpingyourboyfriend.org');
const encoded = Buffer.from('support@helpingyourboyfriend.org').map(byte => byte ^ 0x42).toString('hex');
assert.equal(fingerprint(contact.replace('support@helpingyourboyfriend.org',`<a href="/cdn-cgi/l/email-protection"><span data-cfemail="42${encoded}">[email protected]</span></a>`)),fingerprint(contact),'Cloudflare email protection ignored');
for (const [from, to] of [['Game guide','New description'], ['Title /','New title'], ['/images/a.png','/images/b.png'], ['alt="Adrian"','alt="Ian"'], ['Player guide','Structured game guide'], ['lang="en"','lang="fr"']]) assert.notEqual(fingerprint(html('/').replace(from,to)), fingerprint(html('/')), 'SEO-effective input tracked');
const eligibility = buildManifest([entry('/'), entry('/new'), entry('/controls', html('/controls').replace('index, follow','noindex'))], first, t2);
assert.deepEqual(diff(first, eligibility).added, [`${origin}/new`]);
assert.deepEqual(diff(first, eligibility).deleted, ['/characters','/controls','/endings'].map(p => `${origin}${p}`));
assert.throws(() => buildManifest(candidates, { ...first, generatedAt: t2 }, t1), /predates/);
assert.throws(() => diff(first, { ...same, fingerprintVersion: 'other' }), /migration/);
const migrated = buildManifest(candidates, { ...first, fingerprintVersion: 'legacy' }, t2, { migration: true });
assert.deepEqual(migrated.entries.map(e => e.lastModified), first.entries.map(e => e.lastModified));
const returned = { ...same, entries: same.entries.map(e => ({ ...e, lastModified: t2 })) };
assert.equal(diff(first, returned).updated.length, 4, 'Same fingerprint after content revert is still a notification');
assert.throws(() => validate({ ...first, entries: [{ ...first.entries[0], canonicalUrl: 'https://evil.example/' }] }, origin), /host|origin|path/);
assert.deepEqual(batches(Array.from({length:10001}, (_,i) => i)).map(v => v.length), [10000,1]);
assert.deepEqual(sitemapChunks(Array.from({length:50001}, (_,i) => ({ ...first.entries[0], path: `/page${i}`, canonicalUrl: `${origin}/page${i}` }))).map(v => v.length), [50000,1]);
const huge = {...first,entries:Array.from({length:50001},(_,i)=>({...first.entries[0],path:`/page${i}`,canonicalUrl:`${origin}/page${i}`}))};
assert.equal(sitemapRewrites(huge).beforeFiles[0].source,'/sitemap.xml');
assert.equal((sitemapIndexXml(huge).match(/<sitemap>/g)??[]).length,2);
assert.ok(!sitemapIndexXml(huge).includes('<priority>'),'Sitemap Index must not include URL-only fields');
assert.deepEqual(sitemapRewrites(first).beforeFiles,[],'Current small site has no rewrite');
assert.notEqual(fingerprint(html('/'),{'/images/a.png':'original'}),fingerprint(html('/'),{'/images/a.png':'replacement'}),'Core image content replacement tracked');

console.log('SEO tests passed: semantic changes, noise, dates, migration, exclusions, deletion, and sitemap partition.');
