import { readGuides, topicPath } from './read-guides.mjs';
import fs from "node:fs";
const origin = process.argv[2] ?? process.env.AUDIT_ORIGIN ?? "http://127.0.0.1:3128";
const canonicalOrigin = JSON.parse(fs.readFileSync("planning/route-registry.json", "utf8")).origin;
const officialGameUrl = JSON.parse(fs.readFileSync("data/games/main-game.json", "utf8")).credits.officialUrl;
const guides = readGuides().filter((item) => item.status === "published");
const staticRoutes = ["/privacy", "/terms", "/copyright", "/about", "/contact"];
const routes = ["/", ...staticRoutes, ...guides.map((item) => topicPath(item.id))];
const decode = (value) => value.replaceAll("&amp;", "&").replaceAll("&#x27;", "'").replaceAll("&quot;", '"').replaceAll("&lt;", "<").replaceAll("&gt;", ">");
const text = (html) => decode(html.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim());
const results = [];
const failures = [];
for (const route of routes) {
  const response = await fetch(`${origin}${route}`);
  const html = await response.text();
  const title = decode(html.match(/<title>([\s\S]*?)<\/title>/i)?.[1] ?? "");
  const description = decode(html.match(/<meta[^>]+name="description"[^>]+content="([^"]*)"/i)?.[1] ?? "");
  const canonical = decode(html.match(/<link[^>]+rel="canonical"[^>]+href="([^"]+)"/i)?.[1] ?? "");
  const ogUrl = decode(html.match(/<meta[^>]+property="og:url"[^>]+content="([^"]+)"/i)?.[1] ?? "");
  const h1s = [...html.matchAll(/<h1[^>]*>([\s\S]*?)<\/h1>/gi)].map((match) => text(match[1]));
  const mains = [...html.matchAll(/<main\b/gi)].length;
  const jsonLd = [...html.matchAll(/<script[^>]+type="application\/ld\+json"[^>]*>([\s\S]*?)<\/script>/gi)].map((match) => JSON.parse(decode(match[1])));
  const externalAnchors = [...html.matchAll(/<a[^>]+href="(https?:\/\/[^"#]+)"/gi)].map((match) => match[1]);
  const thirdPartyFrames = [...html.matchAll(/<iframe[^>]+src="([^"]+)"/gi)].map((match) => decode(match[1]));
  const legalRelMatches = [...html.matchAll(/<a[^>]+href="\/(privacy|terms|copyright|about|contact)"[^>]+rel="([^"]+)"/gi)].map((match) => match[2]);
  const record = { route, status: response.status, title, titleLength: [...title].length, descriptionLength: [...description].length, h1s, mains, canonical, ogUrl, jsonLdTypes: jsonLd.flatMap((item) => item["@graph"]?.map((entry) => entry["@type"]) ?? [item["@type"]]), externalAnchors, thirdPartyFrames, legalRelMatches };
  results.push(record);
  const expectedCanonical = route === "/" ? canonicalOrigin : new URL(route, canonicalOrigin).toString();
  if (response.status !== 200) failures.push(`${route}:status-${response.status}`);
  if (record.titleLength < 40 || record.titleLength > 60) failures.push(`${route}:title-${record.titleLength}`);
  if (record.descriptionLength < 140 || record.descriptionLength > 160) failures.push(`${route}:description-${record.descriptionLength}`);
  if (h1s.length !== 1) failures.push(`${route}:h1-${h1s.length}`);
  if (mains !== 1) failures.push(`${route}:main-${mains}`);
  if (canonical !== expectedCanonical || ogUrl !== expectedCanonical) failures.push(`${route}:url-signal`);
  if (!jsonLd.length) failures.push(`${route}:jsonld-missing`);
  if (externalAnchors.some(url => url !== officialGameUrl)) failures.push(`${route}:unexpected-external-anchor`);
  if (legalRelMatches.length !== 5 || legalRelMatches.some((value) => value !== "noopener noreferrer nofollow")) failures.push(`${route}:legal-rel`);
  if (route === "/" && thirdPartyFrames.some((src) => !src.startsWith("https://www.youtube-nocookie.com/embed/"))) failures.push(`${route}:unsafe-initial-game-frame`);
}
const sitemapResponse = await fetch(`${origin}/sitemap.xml`);
const sitemapText = await sitemapResponse.text();
const sitemapUrls = [...sitemapText.matchAll(/<loc>([^<]+)<\/loc>/g)].map((match) => match[1]);
const sitemapLastmod = [...sitemapText.matchAll(/<lastmod>([^<]+)<\/lastmod>/g)].map((match) => match[1]);
const expectedUrls = routes.map((route) => route === "/" ? canonicalOrigin : new URL(route, canonicalOrigin).toString());
if (sitemapResponse.status !== 200 || sitemapUrls.length !== routes.length || new Set(sitemapUrls).size !== sitemapUrls.length || expectedUrls.some((url) => !sitemapUrls.includes(url)) || sitemapUrls.some((url) => /\/games(?:\/|$)|\/guides(?:\/|$)/.test(new URL(url).pathname)) || sitemapLastmod.some((date) => !/^\d{4}-\d{2}-\d{2}/.test(date))) failures.push("sitemap-set-or-date");
const removed = await Promise.all(["/games", "/games/going-live", "/guides"].map((path) => fetch(`${origin}${path}`)));
if (removed.some((response) => response.status !== 404)) failures.push("removed-routes");
const robots = await (await fetch(`${origin}/robots.txt`)).text();
if (!robots.includes(`${canonicalOrigin}/sitemap.xml`) || !robots.includes("Allow: /")) failures.push("robots");
const report = { auditedAt: "2026-10-09", origin, canonicalOrigin, routes: results, sitemap: { status: sitemapResponse.status, urls: sitemapUrls, lastModified: sitemapLastmod }, removedStatuses: removed.map((response) => response.status), failures };
fs.writeFileSync("reports/seo-runtime-audit.json", `${JSON.stringify(report, null, 2)}\n`);
console.log(JSON.stringify({ routes: results.length, sitemapUrls: sitemapUrls.length, removedStatuses: report.removedStatuses, failures }, null, 2));
if (failures.length) process.exit(1);
